server:
    port: 8080
spring:
    datasource:
        url: jdbc:mysql://47.98.104.98:3306/flowable?characterEncoding=UTF-8
        username: root
        password: jxZ03121994!
        driver-class-name: com.mysql.cj.jdbc.Driver
flowable:
    async-executor-activate: true
    database-schema-update: true    # 自动升级表结构